#!/bin/sh
# shellcheck disable=SC2155

get_diy_freq() {
  local value="$(cat /sys/devices/system/cpu/cpufreq/policy0/scaling_cur_freq 2>/dev/null)"
  [ -n "$value" ] || value="0"
  echo "$value"
}

get_diy_temp() {
  local value="$(cat /sys/class/thermal/thermal_zone*/temp 2>/dev/null | sort -n | tail -1)"
  [ -n "$value" ] || value="-1"
  echo "$value"
}

case "$1" in
  diy_freq)
    get_diy_freq
    ;;
  diy_temp)
    get_diy_temp | awk '{ printf("%.1f\n", $1/1000) }'
    ;;
  *)
    echo "Usage: $0 {diy_freq|diy_temp}"
    exit 1
    ;;
esac
