#!/bin/sh

# 设置所有网口可访问网页终端
uci delete ttyd.@ttyd[0].interface

# 设置所有网口可连接 SSH
uci set dropbear.@dropbear[0].Interface=''
uci commit



sed -i 's/\"services\"/\"control\"/g' /usr/lib/lua/luci/controller/mia.lua
sed -i 's/\"services\"/\"control\"/g' /usr/lib/lua/luci/controller/appfilter.lua
sed -i 's#downloads.openwrt.org#mirror.nju.edu.cn/immortalwrt#g' /etc/opkg/distfeeds.conf
sed -i '/core/d' /etc/opkg/distfeeds.conf
sed -i '/smpackage/d' /etc/opkg/distfeeds.conf
#sed -i 's/root::0:0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow
#sed -i 's/root:::0:99999:7:::/root:$1$V4UetPzk$CYXluq4wUazHjmCDBCqXF.:0:0:99999:7:::/g' /etc/shadow

date_version=$(date +"%y.%m.%d")
sed -i '/DISTRIB_REVISION/d' /etc/openwrt_release
echo "DISTRIB_REVISION='Vip-Custom-$(date +"%Y.%m.%d")_LG_OpenwrtServer'" >> /etc/openwrt_release
sed -i '/DISTRIB_DESCRIPTION/d' /etc/openwrt_release
echo "DISTRIB_DESCRIPTION='EzOpWrt '" >> /etc/openwrt_release
mv /etc/99-msd_lite /etc/hotplug.d/iface/99-msd_lite
mv /etc/99-udpxy /etc/hotplug.d/iface/99-udpxy
chmod a+rwx /etc/hotplug.d/iface/99-msd_lite
chmod a+rwx /etc/hotplug.d/iface/99-udpxy

#mv /etc/cfg-network /etc/config/network

uci del dhcp.lan.ra_slaac
uci del dhcp.lan.dhcpv6
uci del dhcp.lan.ra_flags
uci add_list dhcp.lan.ra_flags='none'
uci set dhcp.lan.dns_service='0'
uci commit dhcp

uci del network.wan6
uci del network.globals.ula_prefix
uci set network.lan.ip6assign='64'
uci set network.lan.ip6ifaceid='eui64'

uci set network.wan.device='eth0'
uci del network.cfg030f15.ports
uci add_list network.cfg030f15.ports='eth1'
uci add_list network.cfg030f15.ports='eth2'
uci add_list network.cfg030f15.ports='eth3'
uci add_list network.cfg030f15.ports='eth4'
uci add_list network.cfg030f15.ports='eth5'
uci commit network

/etc/init.d/network restart
/etc/init.d/odhcpd restart

exit 0
