#!/bin/sh

uci -q get system.@imm_init[0] > "/dev/null" || uci -q add system imm_init > "/dev/null"

if ! uci -q get system.@imm_init[0].lang > "/dev/null"; then
	uci -q batch <<-EOF
		set luci.main.lang="auto"
		commit luci

		set system.@imm_init[0].lang="1"
		commit system
	EOF
fi

sed -i "/log-facility/d" "/etc/dnsmasq.conf"
echo "log-facility=/dev/null" >> "/etc/dnsmasq.conf"

sed -i 's/mirrors.vsean.net/mirrors.jlu.edu.cn/g' /etc/opkg/distfeeds.conf
sed -i 's/openwrt/immortalwrt/g' /etc/opkg/distfeeds.conf
sed -i '/Powered by/,+4d' /usr/lib/lua/luci/view/themes/argon/footer.htm
sed -i '/Powered by/,+4d' /usr/lib/lua/luci/view/themes/argon/footer_login.htm
sed -i '/Powered by/d' /usr/lib/lua/luci/view/themes/bootstrap/footer.htm
sed -i '/ula_prefix/d' /etc/config/network
sed -i 's/60/64/g' /etc/config/network
sed -ri '/check_signature/s@^[^#]@#&@' /etc/opkg.conf
sed -i 's/3/7/g' /etc/config/autoreboot
sed -i 's/5/3/g' /etc/config/autoreboot
sed -i 's/0/1/g' /etc/config/autoreboot

ln -sf "/sbin/ip" "/usr/bin/ip"

exit 0
