#!/bin/sh

uci -q get system.@imm_init[0] > "/dev/null" || uci -q add system imm_init > "/dev/null"

if ! uci -q get system.@imm_init[0].lang > "/dev/null"; then
	uci -q batch <<-EOF
		set luci.main.lang="auto"
		commit luci

		set system.@imm_init[0].lang="1"
		commit system
	EOF
fi

sed -i "/log-facility/d" "/etc/dnsmasq.conf"
echo "log-facility=/dev/null" >> "/etc/dnsmasq.conf"

sed -i '/Powered by/,+4d' /usr/lib/lua/luci/view/themes/argon/footer.htm
sed -i '/Powered by/,+4d' /usr/lib/lua/luci/view/themes/argon/footer_login.htm
sed -i '/Powered by/d' /usr/lib/lua/luci/view/themes/bootstrap/footer.htm

ln -sf "/sbin/ip" "/usr/bin/ip"

exit 0
